site_name: Qavvali | قوَّالی
site_url: https://qavvali.com/
site_author: Vishal | وشال
theme:
  name: material
  font:
    text: Albert Sans
  icon:
    logo: material/library
  favicon: images/icons8-poem-stickers-32.png
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    # - navigation.tabs
    - search.suggest
    - search.share
    - search.highlight
    - header.autohide
plugins:
  - search
  - tags:
      tags_file: tags.md
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - smarty
  - tables
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - attr_list
extra_css:
  - stylesheets/extra.css
  - stylesheets/details.css
extra:
  analytics:
    provider: google
    property: G-RWK4ZW9BCD